### ISSUE TITLE
Deploy pdpdmeetup.com

### ISSUE THREAD

**Issue by robinchew** [mattharley/pdpdmeetup#20]
pdpdmeetup.com still redirects to github. It should start serving the awesome codes. The index page can have a link to this github page.

**Comment by Mause** [comment]
Missed the deployment meetup, at what url is it currently available?

**Comment by robinchew** [comment]
Good question!

**Comment by mattharley** [comment]
The URL is: http://pdpdmeetup.herokuapp.com

On Friday, 8 July 2016, robinchew <notifications@github.com> wrote:

> Good question!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mattharley/pdpdmeetup/issues/20#issuecomment-231333350>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArt9AzF-GcZgjcYI7R5QJatnWm3YAyiks5qTi43gaJpZM4JHRMr>
> .
>


-- 
Matt Harley
-----------------------------
matt@mattharley.com
mobile: +61 421 933 877
skype: matt.harley

Currently I'm the chief tech guy at hipflask
Website/blog: http://www.hipflaskapp.com/  <http://www.hipflaskapp.com/>
iOS: http://apple.co/12XnhZn
Android: http://bit.ly/1plwrbP

**Comment by robinchew** [comment]
Shall we make it pdpdmeetup.com?

**Comment by mattharley** [comment]
sure!

On 8 July 2016 at 19:10, robinchew <notifications@github.com> wrote:

> Shall we make it pdpdmeetup.com?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mattharley/pdpdmeetup/issues/20#issuecomment-231334676>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArt9BdEDJN-dTFXyAwI57WUOq6luSNuks5qTjAbgaJpZM4JHRMr>
> .
>



-- 
Matt Harley
-----------------------------
matt@mattharley.com
mobile: +61 421 933 877
skype: matt.harley

Currently I'm the chief tech guy at hipflask
Website/blog: http://www.hipflaskapp.com/  <http://www.hipflaskapp.com/>
iOS: http://apple.co/12XnhZn
Android: http://bit.ly/1plwrbP

**Comment by mattharley** [comment]
@robinchew i've gone one better and setup SSL!

https://www.pdpdmeetup.com/

**Comment by robinchew** [comment]
Thanks! I wanna merge a PR and do a deploy, but I'm not sure what to do on the heroku CLI. I got the heroku command line, and pulled down mattharley/pdpdmeetup.git, not sure what to do next. Hope you can help me out on Slack or we meet up sometime.
