### ISSUE TITLE
Profiles page

### ISSUE THREAD

**Issue by robinchew** [mattharley/pdpdmeetup#7]
Page with a list of profiles of Python Developers. Custom auth model required.

**Comment by Deathridge** [comment]
Ill take a look at this one Robin, as we discussed on thursday.

what sort of auth model were you thinking?

**Comment by robinchew** [comment]
Coooool. Just a custom user model in a custom app. See what names you can come up with. Extra fields include **photo** and whatever we haven't thought of yet. I would also use **email** as the username instead. https://docs.djangoproject.com/en/1.9/topics/auth/customizing/

**Comment by robinchew** [comment]
Another field: **year_started_learning_python**

**Comment by robinchew** [comment]
**year_gave_up_learning_python**

**Comment by robinchew** [comment]
[profile-list.pdf](https://github.com/mattharley/pdpdmeetup/files/252311/profile-list.pdf)

**Comment by Deathridge** [comment]
![capture](https://cloud.githubusercontent.com/assets/7744546/15139698/0fc7e7d2-16ca-11e6-9900-8706383f7ba5.JPG)

a rough sample of where it is now

**Comment by robinchew** [comment]
Hehe I was joking about the **year_gave_up_learning_python** field, but cool!

**Comment by robinchew** [comment]
I couldn't mark this issue as assigned to Mr. Deathridge. So I've marked it as myself, but really it's not.

**Comment by Deathridge** [comment]
This is all sorted now.
